name: main-to-release
on:
  push:
    branches:
      - main

jobs:
  merge_main_to_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          ref: main

      - name: Setup Git user
        run: |
          git config user.name  "action"
          git config user.email "action@github.com"
          git config pull.rebase false

      - name: Merge main into release
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -eux
          eval "$(ssh-agent)"
          ssh-add - <<< $SSH_PRIVATE_KEY
          git fetch origin release --unshallow
          git checkout release
          git pull
          git log main --oneline
          git log release --oneline
          git merge --no-ff main -m "Auto-merge main into release"
          git push origin release
