name: preprocessing-data
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          ref: release

      - name: Get data
        run: |
          ./scripts/get_data.sh

      - name: Count changes
        id: changes
        run: |
          set -x
          git add -N .
          echo "count=$(git diff --name-only ./public/data | wc -l)" >> $GITHUB_OUTPUT

      - name: Setup Git user
        run: |
          git config user.name  "action"
          git config user.email "action@github.com"

      - name: "git commit & push"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          eval "$(ssh-agent)"
          ssh-add - <<< $SSH_PRIVATE_KEY
          git commit ./public/data -m "fetch data $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
          git push
        if: ${{ steps.changes.outputs.count > 0 }}
